adam_kwargs:
  lr: 0.001
batch_sizes:
  64: 32
checkpoint_root: ./data/checkpoint/dpa/xray_ct_lung/final/wo_pg_with_L1/weight_0.100/class_subset/run_0
dec:
  kwargs:
    inner_dims:
    - 64
    - 32
    - 32
    - 32
    - 16
    - 16
    - 16
  type: residual18
early_stoping_patience: 1000000
early_stopping_min_delta: 0.001
early_stopping_patience: 3
enc:
  kwargs:
    inner_dims:
    - 16
    - 16
    - 16
    - 32
    - 32
    - 32
    - 64
  type: residual18
finetune_from: null
image_dim: 1
image_rec_loss:
  loss_kwargs:
    loss_1:
      loss_kwargs:
        use_smooth_pg: false
        weights_per_resolution:
          64:
            feature_weights:
              r32: 1
              r42: 1
            img_weight: 0
      loss_type: relative_perceptual_L1
      loss_weight: 1
    loss_2:
      loss_kwargs: {}
      loss_type: l1
      loss_weight: 0.1
  loss_type: compose
image_sample_iter: 1000
initial_image_res: 64
iters_per_res:
  64:
    stab: 16000
latent_dim: 128
latent_res: 1
log_iter: 10
log_root: ./data/logs/dpa/xray_ct_lung/final/wo_pg_with_L1/weight_0.100/class_subset/run_0
max_image_res: 64
random_seed: 8499
results_root: ./data/results/dpa/xray_ct_lung/final/wo_pg_with_L1/weight_0.100/class_subset/run_0
stab_iter: 100000
test_batch_size: 32
test_datasets:
  anomaly:
    dataset_kwargs:
      cache_data: false
      image_root: /data1/COVID_data_zyh/
      split: test
      split_root: ./folds/train_test_split/anomaly/
    dataset_type: nih
    transform_kwargs:
      crop_size: 224
      equalize_hist: false
      resize: 64
  normal:
    dataset_kwargs:
      cache_data: false
      image_root: /data1/COVID_data_zyh/
      split: test
      split_root: ./folds/train_test_split/normal/
    dataset_type: nih
    transform_kwargs:
      crop_size: 224
      equalize_hist: false
      resize: 64
test_model_path: ./data/checkpoint/dpa/xray_ct_lung/final/wo_pg_with_L1//weight_0.100/class_subset/run_0/anomaly_detection.tar
train_dataset:
  dataset_kwargs:
    cache_data: false
    image_root: /data1/COVID_data_zyh/
    split: train
    split_root: ./folds/train_test_split/normal/
  dataset_type: nih
  transform_kwargs:
    crop_size: 224
    equalize_hist: false
    resize: 64
trns_iter: 0
val_dataset:
  dataset_kwargs:
    cache_data: false
    image_root: /data1/COVID_data_zyh/
    split: train
    split_root: ./folds/train_test_split/normal/
  dataset_type: nih
  transform_kwargs:
    crop_size: 224
    equalize_hist: false
    resize: 64
val_iter: 1000000
verbose: true
